defmodule Rail.Domain.ChatTurn do
  @moduledoc """
  Models a single conversational turn or log event in a role transcript.

  Attributes:
    - `role`: `:user`, `:agent`, or `:system`
    - `author`: `:human`, `:role`, `:activity`, or `:event`
    - `content`: Text content of the turn
    - `text`: Alias of content for compatibility
    - `timestamp`: Optional timestamp
    - `usage`: Optional `TaskUsage` accounting
    - `handoff`: Optional `HandoffLine` associated with this turn
  """
  use Ecto.Schema

  import Ecto.Changeset

  alias Rail.Domain.HandoffLine
  alias Rail.Domain.TaskUsage

  @derive Jason.Encoder

  @roles [:user, :agent, :system]
  @authors [:human, :role, :activity, :event]

  @primary_key false
  embedded_schema do
    field :role, Ecto.Enum, values: @roles, default: :agent
    field :author, Ecto.Enum, values: @authors, default: :role
    field :content, :string, default: ""
    field :text, :string, default: ""
    field :timestamp, :utc_datetime_usec

    embeds_one :usage, TaskUsage
    embeds_one :handoff, HandoffLine
  end

  @fields [:role, :author, :content, :text, :timestamp]

  @doc "Builds a changeset for a ChatTurn."
  def changeset(turn, attrs) do
    turn
    |> cast(attrs, @fields)
    |> sync_text_and_content()
    |> validate_required([:role, :content])
    |> cast_embed(:usage)
    |> cast_embed(:handoff)
  end

  @doc "Builds a valid ChatTurn fixture struct for testing."
  def factory do
    %__MODULE__{
      role: :user,
      author: :human,
      content: "Please update the primary button color.",
      text: "Please update the primary button color.",
      timestamp: DateTime.utc_now()
    }
  end

  @doc "Returns true if the turn was authored by a human / user."
  def user?(%__MODULE__{role: :user}), do: true
  def user?(_other), do: false

  @doc "Returns true if the turn was generated by the role / agent."
  def agent?(%__MODULE__{role: :agent}), do: true
  def agent?(_other), do: false

  @doc "Returns true if the turn is a system event or tool activity."
  def system?(%__MODULE__{role: :system}), do: true
  def system?(_other), do: false

  @doc "Returns true if author is :human."
  def human?(%__MODULE__{author: :human}), do: true
  def human?(_other), do: false

  @doc "Returns true if author is :role."
  def role?(%__MODULE__{author: :role}), do: true
  def role?(_other), do: false

  @doc "Returns true if author is :activity."
  def activity?(%__MODULE__{author: :activity}), do: true
  def activity?(_other), do: false

  @doc "Returns true if author is :event."
  def event?(%__MODULE__{author: :event}), do: true
  def event?(_other), do: false

  @doc "Re-exposes the handoff role ID when this turn represents a HandoffLine."
  def handoff_role_id(%__MODULE__{handoff: %HandoffLine{role_id: role_id}}), do: role_id
  def handoff_role_id(%__MODULE__{}), do: nil

  defp sync_text_and_content(changeset) do
    content = get_field(changeset, :content)
    text = get_field(changeset, :text)

    cond do
      is_binary(content) and (is_nil(text) or text == "") ->
        put_change(changeset, :text, content)

      is_binary(text) and (is_nil(content) or content == "") ->
        put_change(changeset, :content, text)

      true ->
        changeset
    end
  end
end
