apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rail.fullname" . }}
  labels:
    {{- include "rail.labels" . | nindent 4 }}
data:
  PHX_HOST: {{ .Values.env.PHX_HOST | quote }}
  PORT: {{ .Values.env.PORT | quote }}
  PHX_SERVER: {{ .Values.env.PHX_SERVER | quote }}
  POOL_SIZE: {{ .Values.env.POOL_SIZE | quote }}
  AXIS_NO_DISPATCH: {{ .Values.env.AXIS_NO_DISPATCH | quote }}
