{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rail.fullname" . }}
  labels:
    {{- include "rail.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  SECRET_KEY_BASE: {{ .Values.secrets.secretKeyBase | quote }}
  CLOAK_KEY_V1: {{ .Values.secrets.cloakKeyV1 | quote }}
{{- end }}
