defmodule Rail.Roles.RoleInstructionProposal do
  @moduledoc """
  Proposal for revised role instructions generated by an AI improvement run.
  """

  @enforce_keys [:role_id, :model_id, :current, :proposed, :rationale, :diff]
  defstruct [
    :role_id,
    :model_id,
    :current,
    :proposed,
    :rationale,
    :diff,
    sources: [],
    usage: %{}
  ]
end
